# Site settings
title: Wojciech Nowicki
email: contact@wojciechnowicki.com
author:
  name: Wojciech Nowicki
  url: https://wojciechnowicki.com
  twitter: wonowicki
  github: wnowicki
description: >- # this means to ignore newlines until "baseurl:"
  Wojciech Nowicki personal website and blog. A mixture of a strong software engineer, enthusiastic researcher and reputable leader.
keywords: IT, PHP, agile, oop, Raspberry Pi, photography, scrum, software development, software architecture, e-commerce, git, opensource
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wojciechnowicki.com" # the base hostname & protocol for your site

timezone: "Europe/Warsaw" # e.g. "America/New_York"
# Build settings
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin
  - jemoji
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-target-blank
  - jekyll_version_plugin
  - jekyll-toc
markdown: kramdown
permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/page-:num/"
# page_excerpts: true

jekyll_admin:
    homepage: "index"
    hidden_links:
      - datafiles

# Personalisation
social:
    twitter:
        footer: false
        url: https://twitter.com/wonowicki
        icon: fa-brands fa-twitter
    bluesky:
        footer: true
        url: https://bsky.app/profile/wnowicki.bsky.social
        icon: fa-brands fa-bluesky
    linkedin:
        footer: true
        url: https://linkedin.com/in/wonowicki
        icon: fa-brands fa-linkedin
    github:
        footer: true
        url: https://github.com/wnowicki
        icon: fa-brands fa-github
    discord:
        footer: false
        url: https://discord.com/users/985806052354306059
        icon: fa-brands fa-discord
    scholar:
        footer: true
        url: https://scholar.google.com/citations?hl=en&user=7EwCf8cAAAAJ
        icon: fa-brands fa-google-scholar
    orcid:
        footer: true
        url: https://orcid.org/0000-0001-8686-8158
        icon: fa-brands fa-orcid
    facebook:
        footer: false
        url: https://www.facebook.com/wojciechnowickicom
        icon: fa-brands fa-facebook
    youtube:
        footer: false
        url: https://www.youtube.com/c/WojciechNowicki
        icon: fa-brands fa-youtube
    flickr:
        footer: false
        url: https://www.flickr.com/photos/wnowicki
        icon: fa-brands fa-flickr

languages:
    pl:
        flag: pl
        name: Polski
    en:
        flag: gb
        name: English

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/blog/tags/:name/'
    category: '/blog/categories/:name/'

toc:
  min_level: 2 # default: 1
  max_level: 3 # default: 6

jekyll_compose:
  default_front_matter:
    drafts:
      subtitle:
      post_id:
      author:
      categories:
      heading_image:
      language:
      tags:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
