# Site settings
title: Wojciech Nowicki
email: contact@wojciechnowicki.com
description: > # this means to ignore newlines until "baseurl:"
  Wojciech Nowicki personal website and blog. A mixture of a strong software engineer, enthusiastic researcher and reputable leader.
keywords: IT, PHP, agile, oop, Raspberry Pi, photography, scrum, software development, software architecture, e-commerce, git, opensource
baseurl: "/website" # the subpath of your site, e.g. /blog/
url: "https://wnowicki.github.io" # the base hostname & protocol for your site

# Build settings
plugins: [jekyll-paginate]
markdown: kramdown
gems: [jekyll-paginate]
permalink: /:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/page-:num/"
# page_excerpts: true

# Personalisation
social:
    twitter:
        url: https://twitter.com/wonowicki
    facebook:
        url: https://www.facebook.com/wojciechnowickicom
    github:
        url: https://github.com/wnowicki
    youtube:
        url: https://www.youtube.com/c/WojciechNowicki
    linkedin:
        url: https://linkedin.com/in/wonowicki
    flickr:
        url: https://www.flickr.com/photos/wnowicki
    scholar:
        url: https://scholar.google.com/citations?hl=en&user=7EwCf8cAAAAJ
    orcid:
        url: https://orcid.org/0000-0001-8686-8158

languages:
    pl:
        flag: pl
        name: Polski
    en:
        flag: gb
        name: English

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
